"""
Dashboard for Hybrid Grid Digital Twin simulation outputs.

This module visualizes exported results from this project:
- simulation_results.csv
- ntl_events.csv
- ntl_statistics.csv

Default input folder is results/main_ieee (generated by main.py).
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


def _load_project_outputs(results_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    sim_path = results_dir / "simulation_results.csv"
    events_path = results_dir / "ntl_events.csv"
    stats_path = results_dir / "ntl_statistics.csv"

    if not sim_path.exists():
        raise FileNotFoundError(f"Missing file: {sim_path}")

    sim_df = pd.read_csv(sim_path)

    events_df = pd.read_csv(events_path) if events_path.exists() else pd.DataFrame()
    stats_df = pd.read_csv(stats_path) if stats_path.exists() else pd.DataFrame()

    if "ntl_type" in sim_df.columns:
        sim_df["ntl_type"] = sim_df["ntl_type"].fillna("None")

    return sim_df, events_df, stats_df


def _prepare_timeseries(sim_df: pd.DataFrame) -> pd.DataFrame:
    df = sim_df.copy()
    df["sim_hour"] = (df["day"] - 1) * 24.0 + df["hour"]

    non_ntl = df[df["ntl_loss_kw"] <= 1e-12]

    hourly_baseline = (
        non_ntl.groupby(["node_name", "hour"], as_index=False)["actual_p_kw"]
        .mean()
        .rename(columns={"actual_p_kw": "expected_p_kw"})
    )
    df = df.merge(hourly_baseline, on=["node_name", "hour"], how="left")

    node_baseline = non_ntl.groupby("node_name")["actual_p_kw"].mean().to_dict()
    df["expected_p_kw"] = df["expected_p_kw"].fillna(df["node_name"].map(node_baseline))
    df["expected_p_kw"] = df["expected_p_kw"].fillna(df["actual_p_kw"])

    grouped = (
        df.groupby(["timestep", "sim_hour"], as_index=False)
        .agg(
            actual_total_kw=("actual_p_kw", "sum"),
            measured_total_kw=("measured_p_kw", "sum"),
            expected_total_kw=("expected_p_kw", "sum"),
            ntl_total_kw=("ntl_loss_kw", "sum"),
            comm_loss_pct=("communication_loss", lambda s: float(np.mean(s)) * 100.0),
            convergence_ok=("convergence", "mean"),
        )
        .sort_values("timestep")
    )

    grouped["residual_kw"] = grouped["actual_total_kw"] - grouped["measured_total_kw"]
    return grouped


def _find_suspicious_nodes(sim_df: pd.DataFrame, events_df: pd.DataFrame, stats_df: pd.DataFrame) -> List[str]:
    suspects = set()

    if not events_df.empty and "Node" in events_df.columns:
        suspects.update(events_df["Node"].astype(str).tolist())

    if not stats_df.empty and {"Node", "Total_NTL_Loss_kWh"}.issubset(stats_df.columns):
        ntl_nodes = stats_df.loc[stats_df["Total_NTL_Loss_kWh"] > 0, "Node"].astype(str)
        suspects.update(ntl_nodes.tolist())

    ntl_sum = sim_df.groupby("node_name")["ntl_loss_kw"].sum()
    suspects.update(ntl_sum[ntl_sum > 0].index.astype(str).tolist())

    return sorted(suspects)


def _infer_theft_types(sim_df: pd.DataFrame, events_df: pd.DataFrame) -> Dict[str, str]:
    theft_map: Dict[str, str] = {}

    if not events_df.empty and {"Node", "NTL_Type"}.issubset(events_df.columns):
        for _, row in events_df.iterrows():
            theft_map[str(row["Node"])] = str(row["NTL_Type"])

    if not theft_map:
        non_none = sim_df[sim_df["ntl_type"].astype(str) != "None"]
        if not non_none.empty:
            for node, node_df in non_none.groupby("node_name"):
                theft_map[str(node)] = str(node_df["ntl_type"].mode().iloc[0])

    return theft_map


def _infer_customer_types(sim_df: pd.DataFrame) -> Dict[str, str]:
    """Infer customer classes by known IEEE13 mapping, with power-based fallback."""
    known_map = {
        "634a": "Residential",
        "634b": "Institutional",
        "645": "Commercial",
        "646": "Public Municipal",
        "652": "Agricultural",
        "671": "Industrial",
        "670a": "Bulk",
    }

    inferred: Dict[str, str] = {}
    avg_power = sim_df.groupby("node_name")["actual_p_kw"].mean().to_dict()

    for node_name in sim_df["node_name"].astype(str).unique():
        if node_name in known_map:
            inferred[node_name] = known_map[node_name]
            continue

        p = float(avg_power.get(node_name, 0.0))
        if p < 1.0:
            inferred[node_name] = "Residential"
        elif p < 2.5:
            inferred[node_name] = "Commercial"
        elif p < 4.0:
            inferred[node_name] = "Agricultural"
        else:
            inferred[node_name] = "Industrial"

    return inferred


def _make_wide_frames(sim_df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    df = sim_df.copy()
    df["Hour"] = (df["day"] - 1) * 24.0 + df["hour"]

    baseline_long = (
        df.groupby(["node_name", "hour"], as_index=False)["actual_p_kw"]
        .mean()
        .rename(columns={"actual_p_kw": "baseline_p_kw"})
    )
    df = df.merge(baseline_long, on=["node_name", "hour"], how="left")

    baseline_wide = (
        df.pivot_table(index="Hour", columns="node_name", values="baseline_p_kw", aggfunc="mean")
        .reset_index()
        .sort_values("Hour")
    )

    measured_wide = (
        df.pivot_table(index="Hour", columns="node_name", values="measured_p_kw", aggfunc="mean")
        .reset_index()
        .sort_values("Hour")
    )

    actual_wide = (
        df.pivot_table(index="Hour", columns="node_name", values="actual_p_kw", aggfunc="mean")
        .add_prefix("Actual_")
        .reset_index()
        .sort_values("Hour")
    )

    fraud_wide = measured_wide.merge(actual_wide, on="Hour", how="left")
    return baseline_wide, fraud_wide


def _theft_reason_text(chosen_thefts: Dict[str, str], fraud_df: pd.DataFrame, baseline_df: pd.DataFrame) -> str:
    lines = ["Suspicious Theft Summary:"]
    for node, theft_type in chosen_thefts.items():
        if node not in baseline_df.columns or node not in fraud_df.columns:
            continue

        baseline_avg = baseline_df[node].mean()
        reported_avg = fraud_df[node].mean()
        actual_col = f"Actual_{node}"
        actual_avg = fraud_df[actual_col].mean() if actual_col in fraud_df.columns else reported_avg

        theft_key = theft_type.lower()
        if "bypass" in theft_key:
            reason = (
                f"reported avg {reported_avg:.2f} kW vs expected avg {baseline_avg:.2f} kW, "
                f"suggesting unmetered bypass behavior."
            )
        elif "illegal" in theft_key:
            reason = (
                f"actual avg {actual_avg:.2f} kW vs metered avg {reported_avg:.2f} kW, "
                f"indicating hidden loading."
            )
        elif "tamper" in theft_key:
            reason = (
                f"meter output diverges while consumption remains near baseline, "
                f"suggesting measurement tampering."
            )
        else:
            reason = "metered profile deviates from expected behavior."

        label = theft_type.replace("_", " ")
        lines.append(f"Node {node}: {label} - {reason}")

    return "\n".join(lines)


def _draw_network_panel(
    ax,
    suspicious_nodes: List[str],
    chosen_thefts: Dict[str, str],
    customer_types: Dict[str, str],
    sim_df: pd.DataFrame,
    baseline_df: pd.DataFrame,
    fraud_df: pd.DataFrame,
):
    suspects = set(suspicious_nodes)
    ax.axis("off")
    ax.set_title("Suspicious Asset Map [Red = Suspect]")

    station_box = dict(boxstyle="round,pad=0.4", fc="#f4f6f8", ec="#37474f", lw=1.3)
    feeder_box = dict(boxstyle="round,pad=0.32", fc="#e3f2fd", ec="#1565c0", lw=1.1)
    normal_box = dict(boxstyle="round,pad=0.3", fc="#eceff1", ec="#455a64", lw=1)
    suspect_box = dict(boxstyle="round,pad=0.3", fc="#ffebee", ec="#b71c1c", lw=1.5)

    node_meter = sim_df.groupby("node_name")["meter_type"].agg(lambda s: s.mode().iloc[0]).to_dict()
    all_nodes = sorted(node_meter.keys())
    legacy_nodes = [node for node in all_nodes if node_meter.get(node) != "smart"]
    smart_nodes = [node for node in all_nodes if node_meter.get(node) == "smart"]

    ax.text(0.50, 0.92, "Substation", ha="center", va="center", bbox=station_box, fontsize=10)
    ax.text(0.50, 0.80, "Distribution Transformer", ha="center", va="center", bbox=station_box, fontsize=9)

    ax.text(0.30, 0.68, "Feeder A (Legacy)", ha="center", va="center", bbox=feeder_box, fontsize=8)
    ax.text(0.70, 0.68, "Feeder B (Smart)", ha="center", va="center", bbox=feeder_box, fontsize=8)

    ax.annotate("", xy=(0.50, 0.84), xytext=(0.50, 0.89), arrowprops=dict(arrowstyle="->", color="#607d8b", lw=1.2))
    ax.annotate("", xy=(0.30, 0.71), xytext=(0.50, 0.77), arrowprops=dict(arrowstyle="->", color="#607d8b", lw=1.2))
    ax.annotate("", xy=(0.70, 0.71), xytext=(0.50, 0.77), arrowprops=dict(arrowstyle="->", color="#607d8b", lw=1.2))

    def draw_customers(nodes: List[str], x: float):
        if not nodes:
            return
        y_values = np.linspace(0.58, 0.16, num=len(nodes))
        for y, node in zip(y_values, nodes):
            style = suspect_box if node in suspects else normal_box
            customer_class = customer_types.get(str(node), "Unknown")
            ax.text(x, y, f"Customer {node}\n{customer_class}", ha="center", va="center", bbox=style, fontsize=7.6)
            ax.annotate("", xy=(x, y + 0.025), xytext=(x, 0.65), arrowprops=dict(arrowstyle="->", color="#90a4ae", lw=1.0))

    draw_customers(legacy_nodes, 0.30)
    draw_customers(smart_nodes, 0.70)

    summary = _theft_reason_text(chosen_thefts, fraud_df, baseline_df)
    ax.text(0.02, 0.02, summary, transform=ax.transAxes, fontsize=7, va="bottom", ha="left", family="monospace")


def _plot_expected_meter_stream(ax, baseline_df: pd.DataFrame, nodes: List[str]):
    if not nodes:
        ax.axis("off")
        return

    for node in nodes[:6]:
        if node in baseline_df.columns:
            ax.plot(baseline_df["Hour"], baseline_df[node], label=f"Node {node} Expected", linestyle="--", linewidth=1.4)

    ax.set_xlabel("Simulation Hour")
    ax.set_ylabel("Expected Metered Load (kW)")
    ax.set_title("Expected Meter Stream")
    ax.legend(fontsize=7)
    ax.grid(alpha=0.25)


def _plot_suspected_meter_stream(ax, fraud_df: pd.DataFrame, suspicious_nodes: List[str]):
    if not suspicious_nodes:
        ax.axis("off")
        ax.text(0.5, 0.5, "No suspicious nodes detected.", ha="center", va="center", fontsize=11)
        return

    for node in suspicious_nodes:
        if node in fraud_df.columns:
            ax.plot(fraud_df["Hour"], fraud_df[node], linewidth=2, label=f"Node {node} Metered")

    ax.set_xlabel("Simulation Hour")
    ax.set_ylabel("Suspected Metered Load (kW)")
    ax.set_title("Suspected Meter Stream")
    ax.legend(fontsize=7)
    ax.grid(alpha=0.25)


def _plot_transformer_vs_reported_pie(ax, ts_df: pd.DataFrame):
    avg_actual = float(ts_df["actual_total_kw"].mean())
    avg_reported = float(ts_df["measured_total_kw"].mean())
    avg_expected = float(ts_df["expected_total_kw"].mean())
    avg_ntl = float(ts_df["ntl_total_kw"].mean())

    labels = ["Substation Import (Actual)", "Consumer Metered (Reported)"]
    values = [avg_actual, avg_reported]
    colors = ["#1e88e5", "#ffb300"]

    ax.pie(values, labels=labels, autopct="%1.1f%%", startangle=140, colors=colors, explode=[0.05, 0.05], wedgeprops={"edgecolor": "white"})
    ax.set_title("Transformer Import vs Reported Consumer Load")
    ax.axis("equal")
    ax.text(0, -1.32, f"Avg Actual Import: {avg_actual:.2f} kW\nAvg Expected Import: {avg_expected:.2f} kW\nAvg NTL Residual: {avg_ntl:+.2f} kW", ha="center", va="top", fontsize=8)


def _plot_loss_behavior(ax, ts_df: pd.DataFrame):
    ax.plot(ts_df["sim_hour"], ts_df["ntl_total_kw"], label="NTL Loss (kW)", color="#ef6c00", linewidth=2)
    ax.plot(ts_df["sim_hour"], ts_df["residual_kw"], label="Actual - Metered (kW)", color="#6a1b9a", linewidth=1.7)
    ax.set_xlabel("Simulation Hour")
    ax.set_ylabel("Loss / Residual (kW)")
    ax.set_title("Loss Behavior Across Time")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25)


def _plot_summary_bars(ax, ts_df: pd.DataFrame):
    labels = ["Actual Import", "Expected Import", "Metered", "NTL Loss", "Residual"]
    values = [
        ts_df["actual_total_kw"].mean(),
        ts_df["expected_total_kw"].mean(),
        ts_df["measured_total_kw"].mean(),
        ts_df["ntl_total_kw"].mean(),
        ts_df["residual_kw"].mean(),
    ]
    colors = ["#1e88e5", "#43a047", "#f57c00", "#d32f2f", "#6a1b9a"]

    bars = ax.bar(labels, values, color=colors)
    for bar in bars:
        h = bar.get_height()
        ax.text(bar.get_x() + bar.get_width() / 2.0, h, f"{h:.2f}", ha="center", va="bottom", fontsize=8)

    ax.set_ylabel("Average Power (kW)")
    ax.set_title("Grid Snapshot Balance Matrix")
    ax.grid(axis="y", alpha=0.25)


def _plot_explanation_comparison(ax, fraud_df: pd.DataFrame, baseline_df: pd.DataFrame, suspicious_nodes: List[str], chosen_thefts: Dict[str, str]):
    ax.set_title("Suspicious Explanation Comparison")

    if not suspicious_nodes:
        ax.axis("off")
        ax.text(0.5, 0.5, "No suspicious nodes detected.", ha="center", va="center", fontsize=11)
        return

    x = np.arange(len(suspicious_nodes))
    baseline_avg = [baseline_df[node].mean() if node in baseline_df.columns else 0.0 for node in suspicious_nodes]
    reported_avg = [fraud_df[node].mean() if node in fraud_df.columns else 0.0 for node in suspicious_nodes]
    actual_avg = [fraud_df[f"Actual_{node}"].mean() if f"Actual_{node}" in fraud_df.columns else reported_avg[idx] for idx, node in enumerate(suspicious_nodes)]

    w = 0.22
    ax.bar(x - w, baseline_avg, width=w, label="Expected Avg", color="#4caf50", alpha=0.85)
    ax.bar(x, reported_avg, width=w, label="Reported Avg", color="#ffb300", alpha=0.85)
    ax.bar(x + w, actual_avg, width=w, label="Actual Avg", color="#1e88e5", alpha=0.85)

    theft_labels = [chosen_thefts.get(node, "unknown").replace("_", " ") for node in suspicious_nodes]
    ax.set_xticks(x)
    ax.set_xticklabels([f"{node}\n({label})" for node, label in zip(suspicious_nodes, theft_labels)], rotation=10)
    ax.set_xlabel("Suspicious Node and NTL Type")
    ax.set_ylabel("Average Load (kW)")
    ax.grid(axis="y", alpha=0.25)

    theft_colors = {
        "meter bypass": ("#ffebee", "#b71c1c"),
        "partial meter bypass": ("#ffebee", "#b71c1c"),
        "illegal connection": ("#e3f2fd", "#1565c0"),
        "meter tampering": ("#fff3e0", "#ef6c00"),
        "unknown": ("#ffffff", "#000000"),
    }

    extra_handles = []
    unique = []
    for label in theft_labels:
        key = label.lower()
        if key not in unique:
            unique.append(key)
            face, edge = theft_colors.get(key, theft_colors["unknown"])
            extra_handles.append(Line2D([0], [0], marker="o", color=edge, markerfacecolor=face, markersize=8, markeredgewidth=1.5, linestyle="None", label=label))

    handles, labels = ax.get_legend_handles_labels()
    ax.legend(handles + extra_handles, labels + [h.get_label() for h in extra_handles], fontsize=7, ncol=2, bbox_to_anchor=(0.5, -0.24), loc="upper center", frameon=False)


def _plot_suspect_details(
    ax,
    sim_df: pd.DataFrame,
    baseline_df: pd.DataFrame,
    suspicious_nodes: List[str],
    chosen_thefts: Dict[str, str],
    customer_types: Dict[str, str],
):
    ax.axis("off")
    ax.set_title("Detailed Suspect Node Results")

    if not suspicious_nodes:
        ax.text(0.5, 0.5, "No suspicious nodes detected.", ha="center", va="center", fontsize=11)
        return

    rows = []
    for node in suspicious_nodes:
        theft = chosen_thefts.get(node, "unknown").replace("_", " ")
        customer_class = customer_types.get(str(node), "Unknown")
        node_data = sim_df[sim_df["node_name"].astype(str) == str(node)]
        base_avg = baseline_df[node].mean() if node in baseline_df.columns else node_data["actual_p_kw"].mean()
        rep_avg = node_data["measured_p_kw"].mean()
        diff = rep_avg - base_avg

        active_hours = sorted(node_data.loc[node_data["ntl_loss_kw"] > 0, "hour"].astype(float).round(2).unique().tolist())
        active_txt = ", ".join(str(v) for v in active_hours[:8])
        if len(active_hours) > 8:
            active_txt += ", ..."

        rows.append([f"Node {node}", customer_class, theft, f"{base_avg:.2f}", f"{rep_avg:.2f}", f"{diff:+.2f}", active_txt or "none"])

    table = ax.table(
        cellText=rows,
        colLabels=["Node", "Customer Class", "NTL Type", "Expected Avg", "Metered Avg", "Diff", "Active Hours"],
        cellLoc="center",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.35)


def render_dashboard(results_dir: str = "results/main_ieee", save_path: str | None = None, show: bool = True):
    source = Path(results_dir)
    sim_df, events_df, stats_df = _load_project_outputs(source)

    ts_df = _prepare_timeseries(sim_df)
    suspicious_nodes = _find_suspicious_nodes(sim_df, events_df, stats_df)
    chosen_thefts = _infer_theft_types(sim_df, events_df)
    customer_types = _infer_customer_types(sim_df)
    baseline_df, fraud_df = _make_wide_frames(sim_df)

    node_order = sorted(sim_df["node_name"].astype(str).unique().tolist())

    fig = plt.figure(figsize=(16, 24))
    gs = fig.add_gridspec(4, 2, height_ratios=[1.1, 1.0, 1.0, 1.0])

    ax_network = fig.add_subplot(gs[0, 0])
    ax_expected = fig.add_subplot(gs[0, 1])
    ax_suspected = fig.add_subplot(gs[1, 0])
    ax_loss = fig.add_subplot(gs[1, 1])
    ax_summary = fig.add_subplot(gs[2, 0])
    ax_details = fig.add_subplot(gs[2, 1])
    ax_explain = fig.add_subplot(gs[3, 0])
    ax_pie = fig.add_subplot(gs[3, 1])

    fig.suptitle(
        "Hybrid Grid Digital Twin Dashboard: NTL Monitoring and Metering Intelligence",
        fontsize=15,
        fontweight="bold",
    )

    _draw_network_panel(ax_network, suspicious_nodes, chosen_thefts, customer_types, sim_df, baseline_df, fraud_df)
    _plot_expected_meter_stream(ax_expected, baseline_df, node_order)
    _plot_suspected_meter_stream(ax_suspected, fraud_df, suspicious_nodes)
    _plot_loss_behavior(ax_loss, ts_df)
    _plot_summary_bars(ax_summary, ts_df)
    _plot_suspect_details(ax_details, sim_df, baseline_df, suspicious_nodes, chosen_thefts, customer_types)
    _plot_explanation_comparison(ax_explain, fraud_df, baseline_df, suspicious_nodes, chosen_thefts)
    _plot_transformer_vs_reported_pie(ax_pie, ts_df)

    plt.tight_layout(rect=[0, 0.03, 1, 0.97])

    if save_path:
        save_target = Path(save_path)
        save_target.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_target, dpi=180)
        print(f"Saved dashboard to: {save_target}")

    if show:
        plt.show()
    else:
        plt.close(fig)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render project dashboard from exported simulation files")
    parser.add_argument("--results-dir", default="results/main_ieee", help="Folder containing simulation_results.csv and related files")
    parser.add_argument("--save", default="", help="Optional path to save dashboard image (e.g., results/main_ieee/dashboard.png)")
    parser.add_argument("--no-show", action="store_true", help="Do not open interactive plot window")
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    render_dashboard(
        results_dir=args.results_dir,
        save_path=args.save or None,
        show=not args.no_show,
    )
